//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcinetSuporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPCorrection
    {
        public long CorrectionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long BugDocumentId { get; set; }
        public long VersionId { get; set; }
    
        public virtual Documeto Documeto { get; set; }
        public virtual Version Version { get; set; }
    }
}
