//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcinetSuporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public long DepartamentoID { get; set; }
        public string Nome { get; set; }
        public long ResponsavelId { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
    }
}
