//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcinetSuporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documeto()
        {
            this.APPCorrections = new HashSet<APPCorrection>();
            this.APPFeatures = new HashSet<APPFeature>();
        }
    
        public long DocumentId { get; set; }
        public long TipoDocumentoId { get; set; }
        public long BAreaId { get; set; }
        public long ClientId { get; set; }
        public long ClientContactId { get; set; }
        public string TicketId { get; set; }
        public Nullable<long> ResponsavelId { get; set; }
        public bool Orcamentado { get; set; }
        public long OrcamentadoPor { get; set; }
        public Nullable<long> AdjudicadoPor { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<System.DateTime> EspectedDate { get; set; }
        public Nullable<long> StateId { get; set; }
        public double Progress { get; set; }
        public Nullable<System.DateTime> AdjudicadoEm { get; set; }
        public Nullable<System.DateTime> OrcamentadoEm { get; set; }
        public string Assunto { get; set; }
        public string Descricao { get; set; }
        public string DescricaoFact { get; set; }
        public string DescricaoTec { get; set; }
        public Nullable<long> TempoPrevisto { get; set; }
        public Nullable<long> TempoImputar { get; set; }
        public Nullable<long> TempoGasto { get; set; }
        public long PriorityId { get; set; }
        public bool Visible { get; set; }
        public bool System { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPCorrection> APPCorrections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPFeature> APPFeatures { get; set; }
        public virtual BArea BArea { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientContact ClientContact { get; set; }
        public virtual ClientContact ClientContact1 { get; set; }
        public virtual Colaborador Colaborador { get; set; }
        public virtual Colaborador Colaborador1 { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual State State { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
